apiVersion: v1
kind: Namespace
metadata:
  name: demo-keda
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: demo-keda
  name: auto-scaled-deployment
  labels:
    app: auto-scaled-deployment
spec:
  replicas: 0
  selector:
    matchLabels:
      app: auto-scaled-deployment
  template:
    metadata:
      labels:
        app: auto-scaled-deployment
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          requests:
            cpu: 100m
            memory: 500Mi
          limits:
            cpu: 200m
            memory: 600Mi
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: demo-keda
  namespace: demo-keda
spec:
  scaleTargetRef:
    name: auto-scaled-deployment
  minReplicaCount: 0
  maxReplicaCount: 10
  triggers:
  - type: kubernetes-workload
    metadata:
      podSelector: 'app=monitored-deployment'
      value: '1'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: demo-keda
  name: monitored-deployment
  labels:
    app: monitored-deployment
spec:
  replicas: 0
  selector:
    matchLabels:
      app: monitored-deployment
  template:
    metadata:
      labels:
        app: monitored-deployment
    spec:
      containers:
      - name: nginx
        image: nginx